id: IF416E2C2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T14:17:36+00:00'
last_modified: '2022-06-08T07:51:48.512911+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18712
  title: ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་རྩ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    04D4:
      image_group_id: I8LS18714
      title: ''
      total_pages: 99
      order: 1
      base_file: 04D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
